name: travel-planner

services:
  app:
    container_name: travel-planner
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=travel-planner.py
      - FLASK_ENV=development
      - DATABASE_URL=mysql+pymysql://travel-db:${DATABASE_PASSWORD}@db/travel-db
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports:
      - "5000:5000"
    depends_on:
      - db
      - elasticsearch

    networks:
      - travel-network

  db:
    image: mysql:9.1
    container_name: travel-db
    environment:
      MYSQL_DATABASE: travel-db
      MYSQL_USER: travel-db
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true  # Optional root password if needed
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - travel-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  # Set Java memory options to avoid memory issues
      - xpack.security.enabled=false  # Disable security features for development
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - travel-network

volumes:
  db_data:
  es_data:

networks:
  travel-network: 
    driver: bridge
