"""Small changes

Revision ID: 06d7b6af097b
Revises: 1608f2948ea8
Create Date: 2024-11-04 12:07:51.175793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d7b6af097b'
down_revision = '1608f2948ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component_trip_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_component_trip_id', 'trip', ['trip_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('component_category', schema=None) as batch_op:
        batch_op.drop_index('ix_component_category_category_name')
        batch_op.create_index(batch_op.f('ix_component_category_category_name'), ['category_name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_component_category_category_name'))
        batch_op.create_index('ix_component_category_category_name', ['category_name'], unique=False)

    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component_trip_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_component_trip_id', 'trip', ['trip_id'], ['id'])

    # ### end Alembic commands ###
