"""empty message

Revision ID: 1608f2948ea8
Revises: 04f47685125e
Create Date: 2024-10-27 21:18:22.031953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1608f2948ea8'
down_revision = '04f47685125e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('preferred_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('preferred_currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)

    # ### end Alembic commands ###
