"""Added participant_id to component table

Revision ID: 42b2faa1502d
Revises: 8ab061cb44b4
Create Date: 2024-11-22 20:13:32.125270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42b2faa1502d'
down_revision = '8ab061cb44b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_component_participant_id'), ['participant_id'], unique=False)
        batch_op.create_foreign_key('fk_component_participant_id', 'participant', ['participant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('component', schema=None) as batch_op:
        batch_op.drop_constraint('fk_component_participant_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_component_participant_id'))
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
