"""Added new participant table

Revision ID: 8ab061cb44b4
Revises: 2c7e14750789
Create Date: 2024-11-22 17:33:21.406495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ab061cb44b4'
down_revision = '2c7e14750789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('participant_name', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], name='fk_participant_trip_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participant_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participant_trip_id'))

    op.drop_table('participant')
    # ### end Alembic commands ###
