"""Deleted currency_from field in exchange rates

Revision ID: 8f8aa2698bc2
Revises: af5c197a8c1e
Create Date: 2024-11-15 14:27:14.878042

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f8aa2698bc2'
down_revision = 'af5c197a8c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.drop_column('currency_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency_from', mysql.VARCHAR(length=3), nullable=False))

    # ### end Alembic commands ###
