"""Changed field precision in exchangerates table

Revision ID: cde4e8325a6c
Revises: 8f8aa2698bc2
Create Date: 2024-11-15 15:05:09.236275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cde4e8325a6c'
down_revision = '8f8aa2698bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=mysql.DECIMAL(precision=10, scale=6),
               type_=sa.DECIMAL(precision=18, scale=9),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exchange_rates', schema=None) as batch_op:
        batch_op.alter_column('rate',
               existing_type=sa.DECIMAL(precision=18, scale=9),
               type_=mysql.DECIMAL(precision=10, scale=6),
               existing_nullable=False)

    # ### end Alembic commands ###
